### ISSUE TITLE
Tag releases according to SemVer

### ISSUE THREAD

**Issue by mattt** [SalehAlbuga/azure-functions-swift#12]
From the project's [list of releases](https://github.com/SalehAlbuga/azure-functions-swift/releases), it looks like new versions are being tagged with a `v` prefix (e.g. `v0.1.5`). However, Swift Package Manager expects tagged releases to correspond to a valid Semantic Version number. 

According to the [Semantic Versioning specification](https://semver.org):

> ### Is “v1.2.3” a semantic version?
>
> No, “v1.2.3” is not a semantic version. However, prefixing a semantic version with a “v” is a common way (in English) to indicate it is a version number. Abbreviating “version” as “v” is often seen with version control. Example: git tag v1.2.3 -m "Release version 1.2.3", in which case “v1.2.3” is a tag name and the semantic version is “1.2.3”.

Although Swift Package Manager is currently able to resolve tags with `v` prefixes for `exact` requirements, I've seen issues crop up in other libraries (e.g. https://github.com/groue/GRDB.swift/issues/364).

To maintain compatibility with existing versions, I'd recommend making this change prospectively, such that all future versions use SemVer tags.

**Comment by SalehAlbuga** [comment]
@mattt thank you for pointing this out. Yes I actually had issues with it while testing with the latest beta. All future releases are going to use SemVer tags, starting with the most recently released beta! Let me know if you have any feedback if you get to experiment with it. I'm finalizing the next major version release of the framework and the CLI tools

**Comment by mattt** [comment]
Thanks, @SalehAlbuga! I appreciate your making that change.
