### ISSUE TITLE
Support for Windows or Linux?

### ISSUE THREAD

**Issue by panesofglass** [SalehAlbuga/azure-functions-swift#15]
Do you have plans to support this project on Windows (probably via WSL) or Linux? I'd be interested in helping work through the issues and getting it to work. Thank you for building this!

**Comment by SalehAlbuga** [comment]
@panesofglass Thanks a lot! Azure Functions for Swift support Linux and are actually deployed on Linux hosting plans on Azure. The only takeaway, is that developing Swift Functions on Linux is not as easy at the moment as the [Swift Functions CLI Tool](https://github.com/SalehAlbuga/azure-functions-swift-tools) does not support Linux yet (the CLI tool that helps in creating function projects, functions and running them locally). At the moment it's available on macOS with Homebrew `brew install salehalbuga/formulae/swift-func`. 

There are a couple of parts I need to check and rewrite, it's on my todo list & I'm going to keep this thread updated and let you know

Regarding Windows support, as far as I know, Swift native Windows support is set for some release after Swift 5.3. Once there's a dev build available I'll proceed with testing on Windows

**Comment by SalehAlbuga** [comment]
@panesofglass I've updated the tools to work on Linux! Now you can create projects and functions and run them locally on Linux with no hassle! 
Clone the tools repo
```
git clone https://github.com/SalehAlbuga/azure-functions-swift-tools
```

Then install
```
make install 
```

Let me know if you have any feedback!

**Comment by SalehAlbuga** [comment]
Closing the issue as the CLI tools now support Linux
